import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const BUSINESS_NAME = 'Coffee & Tea Inventory Systems';
const REPORT_TITLE = 'Inventory Reports';
const PAGE_MARGIN_X = 42;
const PAGE_TOP = 116;
const PAGE_BOTTOM = 44;
const SECTION_GAP = 18;

const toSafeNumber = (value) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
};

const formatCurrency = (value) =>
  `PHP ${toSafeNumber(value).toLocaleString('en-PH', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

const formatDateTime = (value) =>
  new Intl.DateTimeFormat('en-PH', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(value);

const formatPercent = (value) => `${toSafeNumber(value).toFixed(1)}%`;

const getReportItemStatus = (item) => {
  if (item?.hasExpiredStock) return 'Expired';
  if (item?.isOut) return 'Out of Stock';
  if (item?.isLow) return 'Low Stock';
  return 'Healthy';
};

export const getGeneratorDisplayName = (session) => {
  const directName =
    session?.name || session?.fullName || session?.displayName || session?.userName;

  if (directName) return String(directName).trim();

  const email = String(session?.email || '').trim();
  const localPart = email.split('@')[0].replace(/[._-]+/g, ' ').trim();

  if (!localPart) return 'Inventory Manager';

  return localPart.replace(/\b\w/g, (character) => character.toUpperCase());
};

const blobToMonochromeDataUrl = (blob) =>
  new Promise((resolve, reject) => {
    const objectUrl = URL.createObjectURL(blob);
    const image = new Image();

    image.onload = () => {
      const canvas = document.createElement('canvas');
      const context = canvas.getContext('2d');
      const width = image.naturalWidth || image.width || 256;
      const height = image.naturalHeight || image.height || 256;

      canvas.width = width;
      canvas.height = height;

      context.drawImage(image, 0, 0, width, height);

      const imageData = context.getImageData(0, 0, width, height);
      const { data } = imageData;

      for (let index = 0; index < data.length; index += 4) {
        const grayscale = Math.round(
          data[index] * 0.299 + data[index + 1] * 0.587 + data[index + 2] * 0.114
        );

        data[index] = grayscale;
        data[index + 1] = grayscale;
        data[index + 2] = grayscale;
      }

      context.putImageData(imageData, 0, 0);
      URL.revokeObjectURL(objectUrl);
      resolve(canvas.toDataURL('image/png'));
    };

    image.onerror = () => {
      URL.revokeObjectURL(objectUrl);
      reject(new Error('Failed to load logo image'));
    };

    image.src = objectUrl;
  });

const loadMonochromeLogo = async () => {
  try {
    const response = await fetch('/Logo.png');
    if (!response.ok) {
      throw new Error(`Logo request failed with status ${response.status}`);
    }

    const blob = await response.blob();
    return await blobToMonochromeDataUrl(blob);
  } catch {
    return null;
  }
};

const drawLogoFallback = (doc, x, y) => {
  doc.setDrawColor(0);
  doc.setLineWidth(1);
  doc.roundedRect(x, y, 42, 42, 8, 8);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('C&T', x + 21, y + 25, { align: 'center' });
};

const drawPageChrome = (doc, meta) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const lineEnd = pageWidth - PAGE_MARGIN_X;

  if (meta.logoDataUrl) {
    doc.addImage(meta.logoDataUrl, 'PNG', PAGE_MARGIN_X, 26, 42, 42);
  } else {
    drawLogoFallback(doc, PAGE_MARGIN_X, 26);
  }

  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(BUSINESS_NAME, PAGE_MARGIN_X + 54, 42);
  doc.setFontSize(11);
  doc.text(REPORT_TITLE, PAGE_MARGIN_X + 54, 58);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Generated by: ${meta.generatedBy}`, lineEnd, 40, { align: 'right' });

  if (meta.generatedEmail) {
    doc.text(meta.generatedEmail, lineEnd, 54, { align: 'right' });
  }

  doc.text(`Generated on: ${meta.generatedAtLabel}`, lineEnd, 68, { align: 'right' });
  doc.text(`Export mode: ${meta.modeLabel}`, lineEnd, 82, { align: 'right' });

  doc.setDrawColor(0);
  doc.setLineWidth(1);
  doc.line(PAGE_MARGIN_X, 96, lineEnd, 96);
  doc.line(PAGE_MARGIN_X, pageHeight - 30, lineEnd, pageHeight - 30);

  doc.setFontSize(9);
  doc.text(`Page ${meta.pageNumber} of ${meta.pageCount}`, pageWidth / 2, pageHeight - 17, {
    align: 'center',
  });
};

const ensureVerticalSpace = (doc, currentY, neededHeight) => {
  const pageHeight = doc.internal.pageSize.getHeight();

  if (currentY + neededHeight <= pageHeight - PAGE_BOTTOM) {
    return currentY;
  }

  doc.addPage();
  return PAGE_TOP;
};

const drawSectionTitle = (doc, title, subtitle, y) => {
  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(title, PAGE_MARGIN_X, y);

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(subtitle, PAGE_MARGIN_X, y + 14);
    return y + 26;
  }

  return y + 14;
};

const addTableSection = (doc, { title, subtitle, head, body, startY }) => {
  let currentY = ensureVerticalSpace(doc, startY, 92);
  const tableStartY = drawSectionTitle(doc, title, subtitle, currentY) + 8;

  autoTable(doc, {
    startY: tableStartY,
    head: [head],
    body,
    showHead: 'everyPage',
    margin: {
      top: PAGE_TOP,
      bottom: PAGE_BOTTOM,
      left: PAGE_MARGIN_X,
      right: PAGE_MARGIN_X,
    },
    styles: {
      font: 'helvetica',
      fontSize: 8.2,
      textColor: 20,
      cellPadding: 4,
      lineColor: 150,
      lineWidth: 0.35,
      overflow: 'linebreak',
      valign: 'middle',
    },
    headStyles: {
      fillColor: [255, 255, 255],
      textColor: 0,
      fontStyle: 'bold',
      lineColor: 0,
      lineWidth: 0.7,
    },
    alternateRowStyles: {
      fillColor: [246, 246, 246],
    },
    theme: 'grid',
  });

  return (doc.lastAutoTable?.finalY || tableStartY) + SECTION_GAP;
};

const drawChartFrame = (doc, x, y, width, height, title, subtitle) => {
  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text(title, x, y);

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(subtitle, x, y + 14);
  }

  const frameY = y + 24;
  doc.setDrawColor(0);
  doc.setLineWidth(0.9);
  doc.roundedRect(x, frameY, width, height, 8, 8);

  return frameY;
};

const drawLineChart = (doc, { title, subtitle, data, x, y, width, height }) => {
  const frameY = drawChartFrame(doc, x, y, width, height, title, subtitle);
  const chartX = x + 38;
  const chartY = frameY + 20;
  const chartWidth = width - 56;
  const chartHeight = height - 42;
  const safeData = Array.isArray(data) ? data : [];
  const maxValue = Math.max(1, ...safeData.map((entry) => toSafeNumber(entry.count)));
  const usableData =
    safeData.length > 1 ? safeData : [{ label: 'N/A', count: 0 }, { label: 'N/A', count: 0 }];

  doc.setDrawColor(210);
  doc.setLineWidth(0.45);

  for (let step = 0; step <= 4; step += 1) {
    const lineY = chartY + (chartHeight / 4) * step;
    doc.line(chartX, lineY, chartX + chartWidth, lineY);

    const labelValue = Math.round(maxValue - (maxValue / 4) * step);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(90);
    doc.text(String(labelValue), chartX - 8, lineY + 3, { align: 'right' });
  }

  doc.setDrawColor(0);
  doc.setLineWidth(0.75);
  doc.line(chartX, chartY, chartX, chartY + chartHeight);
  doc.line(chartX, chartY + chartHeight, chartX + chartWidth, chartY + chartHeight);

  const stepX = usableData.length > 1 ? chartWidth / (usableData.length - 1) : chartWidth;
  let previousPoint = null;

  usableData.forEach((entry, index) => {
    const pointX = chartX + stepX * index;
    const pointY =
      chartY + chartHeight - (toSafeNumber(entry.count) / maxValue) * (chartHeight - 8);

    if (previousPoint) {
      doc.setDrawColor(0);
      doc.setLineWidth(1.1);
      doc.line(previousPoint.x, previousPoint.y, pointX, pointY);
    }

    doc.setFillColor(0);
    doc.circle(pointX, pointY, 2.2, 'F');

    if (index % 2 === 0 || index === usableData.length - 1) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(70);
      doc.text(String(entry.label || ''), pointX, chartY + chartHeight + 12, {
        align: 'center',
      });
    }

    previousPoint = { x: pointX, y: pointY };
  });

  return frameY + height;
};

const drawBarChart = (doc, { title, subtitle, data, x, y, width, height }) => {
  const frameY = drawChartFrame(doc, x, y, width, height, title, subtitle);
  const chartX = x + 16;
  const chartY = frameY + 24;
  const chartWidth = width - 32;
  const barHeight = 14;
  const barGap = 16;
  const safeData = Array.isArray(data) ? data.slice(0, 6) : [];

  if (safeData.length === 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('No chart data available.', x + width / 2, frameY + height / 2, {
      align: 'center',
    });
    return frameY + height;
  }

  const maxValue = Math.max(1, ...safeData.map((entry) => toSafeNumber(entry.value)));

  safeData.forEach((entry, index) => {
    const rowY = chartY + index * (barHeight + barGap);
    const label = String(entry.category || 'Other');
    const barWidth = (toSafeNumber(entry.value) / maxValue) * (chartWidth - 110);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(20);
    doc.text(label, chartX, rowY + 10);

    doc.setDrawColor(0);
    doc.setLineWidth(0.45);
    doc.rect(chartX + 76, rowY, chartWidth - 110, barHeight);

    doc.setFillColor(60);
    doc.rect(chartX + 76, rowY, Math.max(4, barWidth), barHeight, 'F');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(60);
    doc.text(formatCurrency(entry.value), chartX + chartWidth, rowY + 10, { align: 'right' });
  });

  return frameY + height;
};

export const downloadReportsPdf = async ({
  mode = 'charts-and-tables',
  stats,
  reportItems,
  categoryPerformance,
  usageData,
  usageMeta,
  topMoving,
  slowMoving,
  needsAttention,
  generatedBy,
  generatedEmail,
}) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
    compress: true,
  });
  const logoDataUrl = await loadMonochromeLogo();
  const generatedAt = new Date();
  const modeLabel =
    mode === 'tables-only' ? 'Tables Only' : 'Graphs and Tables';
  const usageSection = usageMeta || {
    chartTitle: 'Daily stock usage',
    chartSubtitle: 'Adjustments per day - last 14 days',
    sectionTitle: 'Daily Stock Usage',
    columnLabel: 'Day',
  };

  let currentY = PAGE_TOP;
  const pageWidth = doc.internal.pageSize.getWidth();
  const chartWidth = pageWidth - PAGE_MARGIN_X * 2;

  if (mode !== 'tables-only') {
    currentY = drawLineChart(doc, {
      title: usageSection.chartTitle,
      subtitle: `Black-and-white chart view. ${usageSection.chartSubtitle}`,
      data: usageData,
      x: PAGE_MARGIN_X,
      y: currentY,
      width: chartWidth,
      height: 176,
    }) + 24;

    currentY = ensureVerticalSpace(doc, currentY, 240);

    currentY = drawBarChart(doc, {
      title: 'Category Value',
      subtitle: 'Inventory value by category',
      data: categoryPerformance,
      x: PAGE_MARGIN_X,
      y: currentY,
      width: chartWidth,
      height: 200,
    }) + 20;

    doc.addPage();
    currentY = PAGE_TOP;
  }

  currentY = addTableSection(doc, {
    title: 'Summary Table',
    subtitle: 'Core report totals and health indicators',
    head: ['Metric', 'Value'],
    body: [
      ['Total Inventory Value', formatCurrency(stats?.totalValue)],
      ['Active Items', String(toSafeNumber(stats?.activeItems))],
      ['Low Stock Items', String(toSafeNumber(stats?.lowStockItems))],
      ['Out Of Stock Items', String(toSafeNumber(stats?.outOfStockItems))],
      ['Expired Items', String(toSafeNumber(stats?.expiredItems))],
      ['Items Needing Attention', String(toSafeNumber(stats?.attentionItems))],
      ['Stock Turnover', `${toSafeNumber(stats?.stockTurnover).toFixed(1)}x`],
      ['Waste Rate', formatPercent(stats?.wasteRate)],
      ['Health Score', formatPercent(stats?.healthScore)],
    ],
    startY: currentY,
  });

  currentY = addTableSection(doc, {
    title: 'Inventory Items',
    subtitle: 'Detailed item performance and stock condition',
    head: ['Item Name', 'Category', 'Qty', 'Threshold', 'Cost', 'Value', 'Moves', 'Status'],
    body: (Array.isArray(reportItems) ? reportItems : []).map((item) => [
      item.name || 'Unnamed Item',
      item.category || 'Other',
      String(toSafeNumber(item.quantity)),
      String(toSafeNumber(item.threshold)),
      formatCurrency(item.costPrice),
      formatCurrency(item.value),
      String(toSafeNumber(item.adjustmentCount)),
      getReportItemStatus(item),
    ]),
    startY: currentY,
  });

  currentY = addTableSection(doc, {
    title: 'Category Performance',
    subtitle: 'Grouped inventory totals by category',
    head: ['Category', 'Items', 'Quantity', 'Value', 'Share'],
    body: (Array.isArray(categoryPerformance) ? categoryPerformance : []).map((category) => [
      category.category || 'Other',
      String(toSafeNumber(category.items)),
      String(toSafeNumber(category.quantity)),
      formatCurrency(category.value),
      `${toSafeNumber(category.percent).toFixed(1)}%`,
    ]),
    startY: currentY,
  });

  currentY = addTableSection(doc, {
    title: usageSection.sectionTitle,
    subtitle: usageSection.chartSubtitle,
    head: [usageSection.columnLabel, 'Adjustments'],
    body: (Array.isArray(usageData) ? usageData : []).map((entry) => [
      entry.label || '-',
      String(toSafeNumber(entry.count)),
    ]),
    startY: currentY,
  });

  currentY = addTableSection(doc, {
    title: 'Top Moving Items',
    subtitle: 'Most frequently adjusted inventory items',
    head: ['Item Name', 'Category', 'Quantity', 'Adjustment Count'],
    body: (Array.isArray(topMoving) ? topMoving : []).map((item) => [
      item.name || 'Unnamed Item',
      item.category || 'Other',
      String(toSafeNumber(item.quantity)),
      String(toSafeNumber(item.adjustmentCount)),
    ]),
    startY: currentY,
  });

  currentY = addTableSection(doc, {
    title: 'Slow Moving Items',
    subtitle: 'Items with the least recent movement',
    head: ['Item Name', 'Category', 'Quantity', 'Adjustment Count'],
    body: (Array.isArray(slowMoving) ? slowMoving : []).map((item) => [
      item.name || 'Unnamed Item',
      item.category || 'Other',
      String(toSafeNumber(item.quantity)),
      String(toSafeNumber(item.adjustmentCount)),
    ]),
    startY: currentY,
  });

  addTableSection(doc, {
    title: 'Needs Attention',
    subtitle: 'Items that are expired, low on stock, or out of stock',
    head: ['Item Name', 'Category', 'Quantity', 'Threshold', 'Status'],
    body: (Array.isArray(needsAttention) ? needsAttention : []).map((item) => [
      item.name || 'Unnamed Item',
      item.category || 'Other',
      String(toSafeNumber(item.quantity)),
      String(toSafeNumber(item.threshold)),
      getReportItemStatus(item),
    ]),
    startY: currentY,
  });

  const pageCount = doc.getNumberOfPages();
  const generatedAtLabel = formatDateTime(generatedAt);

  for (let pageNumber = 1; pageNumber <= pageCount; pageNumber += 1) {
    doc.setPage(pageNumber);
    drawPageChrome(doc, {
      logoDataUrl,
      generatedBy,
      generatedEmail,
      generatedAtLabel,
      modeLabel,
      pageNumber,
      pageCount,
    });
  }

  const fileDate = generatedAt.toISOString().slice(0, 10);
  doc.save(`inventory-report-${fileDate}.pdf`);
};
